name: 🐞 クロスゼロ不具合報告
description: 不具合内容の詳細を記載してください。
title: "bug: "
labels: ["🐞❔ unconfirmed bug"]
body:
  - type: textarea
    attributes:
      label: 不具合発生環境情報
      description: |
        不具合発生時の環境情報を記入してください
        ```bash
        使用機材・動作環境・OS・ブラウザ・アプリのバージョンなど
        ```
    validations:
      required: true
  - type: textarea
    attributes:
      label: 不具合内容の詳細
      description: 不具合の内容を具体的に記載してください。
    validations:
      required: true
  - type: textarea
    attributes:
      label: 再現手順
      description: |
        不具合内容の発生手順を具体的に記載してください。
        例:
        1. 〇〇ページにアクセス
        2. 〇〇ボタンをクリック
        3. ××という動作が発生する
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
      ### 添付資料 
      description: 不具合に関するスクリーンショットや動画ファイルなどがあれば添付してください。
    validations:
      required: true
  - type: textarea
    attributes:
      label: その他情報
      description: 不具合に関するその他の情報を記載してください。
